### PR TITLE
revert #64 w/ updates (add `mordred` back)

### PR DESCRIPTION
**Pull request by JacksonBurns**
## Changelogs

this reverses many of the changes made in PR #64 to remove `mordred`, with the only differences being the different name of the package

---

_Checklist:_

- [x] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._
See here: https://github.com/datamol-io/molfeat/issues/63#issuecomment-1646182539
- [x] _Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate)._
- [x] _Update the API documentation if a new function is added, or an existing one is deleted. Eventually consider making a new tutorial for new features._
Changed the demo notebook to use mordred again, not sure where else to update
- [x] _Write concise and explanatory changelogs below._
- [x] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

_discussion related to that PR_
The package is now on conda-forge, as requested.

### CODE REVIEW

**Comment by JacksonBurns** [comment]
I guess I suggest the feature label? Can't add them manually as I am a first-time contributor.

**Review by maclandrol — APPROVED** [review]
Thanks @JacksonBurns,  that looks nice.

**Comment by maclandrol** [comment]
Will merge after the CI is green. 

We use `black` for code formatting, so you would want to run that.

Thanks for the contribution and for maintaining mordred.

**Comment by JacksonBurns** [comment]
> Thanks @JacksonBurns, that looks nice.

Thanks!

> Will merge after the CI is green.
> 
> We use `black` for code formatting, so you would want to run that.
> 
> Thanks for the contribution and for maintaining mordred.

Oops, had mine configured to a non-standard line length. Should be good now.

Happy to help out!

**Pull request merged**
