### PR TITLE
added python-dotenv to pyproject.toml

### LINKED ISSUE #80: dotenv and transformers are not included as dependencies when installing using pip
### Is there an existing issue for this?

- [X] I have searched the existing issues and found nothing

### Bug description

`python-dotenv` is used here:

https://github.com/datamol-io/molfeat/blob/87f90c17456accc18d92e8bd6e51ff44ec3c3c9b/molfeat/store/modelstore.py#L12

however it's not included in the `pyproject.toml`, though it is included in `env.yml`. This results in an error when importing `molfeat`.

```python
ModuleNotFoundError: No module named 'dotenv'
```

### How to reproduce the bug

_No response_

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Molfeat version (e.g., 0.1.0):
#- PyTorch Version (e.g., 1.10.0):
#- RDKit version (e.g., 2022.09.5): 
#- scikit-learn version (e.g.,  1.2.1): 
#- OS (e.g., Linux):
#- How you installed Molfeat (`conda`, `pip`, source):
```

</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kkovary**
## Changelogs
closes #80 
- added `python-dotenv` to `pyproject.toml`

---

_Checklist:_

- [ ] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._
- [ ] _Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate)._
- [ ] _Update the API documentation if a new function is added, or an existing one is deleted. Eventually consider making a new tutorial for new features._
- [ ] _Write concise and explanatory changelogs below._
- [ ] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

_discussion related to that PR_

### CODE REVIEW

**Comment by maclandrol** [comment]
Could you remove the `transfomers` dependency from the basic dependency again ?

**Comment by kkovary** [comment]
@maclandrol I update the PR to resolve your comment

**Comment by maclandrol** [comment]
Thanks. I am currently away. Will review and merge when I am back. Otherwise, please ping @hadim

**Review by maclandrol — APPROVED** [review]

**Comment by maclandrol** [comment]
@kkovary this has been merged into 0.9.4, with #82 to make `transformers` optional too.

**Pull request merged**
