### PR TITLE
101 in memory model loading

### LINKED ISSUE #101: Add support for in-memory model loading without local caching
### Details

In certain environments (for example serverless deployments) local storage is limited or unavailable. Currently, the `ModelStore` class downloads models to a local cache before loading them. Adding functionality to load models directly into memory without saving them to a local cache first would allow for usage of large models in memory-constrained environments.

### PR DESCRIPTION
**Pull request by kkovary**
closes #101

## Changelogs
This PR adds support for loading models directly into memory without saving them to a local cache. This is particularly useful for environments with limited local storage, such as serverless deployments.

Current implementation:
* A new class `InMemoryModelStore` is created, inheriting from `ModelStore`.
* The `download` method is overridden to load model data directly into memory.
* The `load` method is modified to work with the in-memory data.

An alternative approach could be to add a flag to `ModelStore` with something like `in_memory` that when set to `True`, use in-memory loading logic; otherwise, use current caching behavior.

- _enumerate the changes of that PR._

---

_Checklist:_

- [ ] _Was this PR discussed in an issue? It is recommended to first discuss a new feature into a GitHub issue before opening a PR._
- [ ] _Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate)._
- [ ] _Update the API documentation if a new function is added, or an existing one is deleted. Eventually consider making a new tutorial for new features._
- [ ] _Write concise and explanatory changelogs below._
- [ ] _If possible, assign one of the following labels to the PR: `feature`, `fix` or `test` (or ask a maintainer to do it for you)._

---

_discussion related to that PR_

### CODE REVIEW

**Review by maclandrol — CHANGES_REQUESTED** [review]
Great feature ! 


Could you add some test and potentially something in the tutorial to showcase the feature ?

**Comment by maclandrol** [comment]
Also ruff is complaining.

**Comment by kkovary** [comment]
yes definitely!

**Comment by kkovary** [comment]
> Also ruff is complaining.

I made [this](https://github.com/datamol-io/molfeat/pull/102/commits/69a01467b8fa445a723ea8b1610d1e6d176e6c3d) commit to fix the ruff issue

**Comment by maclandrol** [comment]
I will wait for the tutorial to merge.

**Comment by kkovary** [comment]
> I will wait for the tutorial to merge.

I added a short tutorial section for `InMemoryModelStore`

**Review by maclandrol — APPROVED** [review]
LGTM, thanks @kkovary

**Pull request merged**
