### PR TITLE
fix doc site and add etl scripts

### PR DESCRIPTION
**Pull request by maclandrol**
Checklist:

- [x] Was this PR discussed in a issue? It is recommended to first discuss a new feature and let the community know whether you are planning or have started working on it before opening a PR.
- [ ] Add tests to cover the fixed bug(s) or the new introduced feature(s) (if appropriate).
- [ ] Update the API documentation if a new function is added or an existing one is deleted.
- [x] Added a `news` entry.
  - _copy `news/TEMPLATE.rst` to `news/my-feature-or-branch.rst`) and edit it._

---

Doc site should now look like this: 
image

### CODE REVIEW

**Comment by maclandrol** [comment]
To do before `0.8.9` ensure no blindspot on cuda based inference

**Review by cwognum — CHANGES_REQUESTED** [review]
Thank you!

1. I don't like the redundancy from having _both_ tabs and the left-side menu containing the same information. I would either hide the left-side menu if there's only a single item or remove the left-side menu altogether and add "subtabs" to the each tab that appear on hover.
2. I like that you've included the ETL notebooks for transparency sake. Could you add a simple README documenting what these notebooks are for? Currently I don't even know what ETL stands for.

**Comment by cwognum** [comment]
Using [this](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars), we can hide the left-side menu on all pages that have no subpages, but I don't like that the content width then is not consistent. Happy to discuss alternatives!

```markdown
---
hide:
  - navigation
  - toc
---

# Document title
...
```

**Comment by maclandrol** [comment]
> Using [this](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars), we can hide the left-side menu on all pages that have no subpages, but I don't like that the content width then is not consistent. Happy to discuss alternatives!
> 
> ```gfm
> ---
> hide:
>   - navigation
>   - toc
> ---
> 
> # Document title
> ...
> ```

I don't think we should hide the TOC. Without the TOC, single-page navigation is awful, and you don't have id anchors to jump across the header sections in the API or tutorial page. Honestly, I don't like neither the tab only navigation, nor the inconsistency if you decide to hide the single-page section only. Thus the current solution:
- You get fixed width of content and consistency on mobile.
- You can navigate with the tabs, without a redundant empty section for single page
- Since the tab are hidden when you scroll at the bottom, you still get the advantage of the left section navigation
- The section page is auto highlighted and expanded for the page on which you are, while the section of other pages are hidden.

**Comment by maclandrol** [comment]
> Thank you!
> 
> 1. I don't like the redundancy from having _both_ tabs and the left-side menu containing the same information. We simplified the left-side menu on purpose after all by introducing the tabs. I would either hide the left-side menu if there's only a single item or remove the left-side menu altogether and add "subtabs" to the each tab that appear on hover.

See answer above. Having subnav is not impossible, but I fear this is a bit more than trying to retheme using the jinja templates. 

> 2. I like that you've included the ETL notebooks for transparency sake. Could you add a simple README documenting what these notebooks are for? Currently I don't even know what ETL stands for.

ETL means "[Extract, transform, load](https://en.wikipedia.org/wiki/Extract,_transform,_load)] and commonly refer to the set of set of instructions for process or data integration.  Here it corresponds to the process through which we add new models. I will add a note in the developer guideline, but this is intended for developers primarily, not for end users.

**Comment by cwognum** [comment]
> I don't think we should hide the TOC. 

I agree! Sorry for the confusion, copied that over from the example but only meant to hide the left-side menu ("navigation"). 

For me the main reason to switch to tabs is to reduce the "complexity" (number of items) in the left-side menu. In @DomInvivo his words in the initial proposal: "The old docs API is too messy with too many things on the left. (xref: https://github.com/datamol-io/datamol/pull/184)"

I would argue that now we're instead adding complexity by having redundant tabs. I do understand the benefits you list, but in that case why not just disable the tabs again and stick with what we had before? In the end it's a minor change, so feel free to do as you prefer and merge once ready.

> ETL means "[Extract, transform, load](https://en.wikipedia.org/wiki/Extract,_transform,_load)] and commonly refer to the set of set of instructions for process or data integration. Here it corresponds to the process through which we add new models. I will add a note in the developer guideline, but this is intended for developers primarily, not for end users.

Learned something new today! Thank you! All clear! :pray:

**Comment by maclandrol** [comment]
Added the notes on ETL for developers. 

Note that although using different technologies, that the current version unintentionally reproduced what is used in the Volkamer lab CADD tutorial without website (https://projects.volkamerlab.org/teachopencadd/). 

If I can't get 

>  add "subtabs" to the each tab that appear on hover.

to work today, I would likely keep the current version, because Dom's version still has the right panel anyway, so my solution just remove the ugly empty section with repeated page title for single-page section. 

Removing the right section all together without a way to get an hyperlink to pages in those sections seems worse for me. Happy to try implementing any alternative ideas either you or @DomInvivo  might have.

**Comment by cwognum** [comment]
> because Dom's version still has the right panel anyway, so my solution just remove the ugly empty section with repeated page title for single-page section.

Just for clarity: No one wants to remove the right-side panel (i.e. "table of contents").

A final proposal could be to integrate the Table of Contents (right-side) and Navigation (left-side) menus with the [Navigation Integration](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration). I would look like this: 

image

image

One orthogonal comment: Going through the docs today, I saw some other cool features, such as the [Back to Top](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button) button.

**Comment by maclandrol** [comment]
>Just for clarity: No one wants to remove the right-side panel (i.e. "table of contents").

Sorry, I mean the left-side panel (not the TOC in my comment above). 

I like the idea of merging them that you are proposing, and some easier things to do may be to reorganize the docs (For example, `license` as a single tab kinda does not make sense). I will come up with an iteration of your last idea, in next commit a bit later today.

**Comment by maclandrol** [comment]
Fix #55 and docs look better with grouping, pages together.

**Pull request merged**
